2025-05-15 20:41:57 [ERROR] [salesforce_api] - [environment=SANDBOX | timestamp=2025-05-15T20:41:57.764439 | caller=salesforce_api] Erro ao processar leads em massa: invalid literal for int() with base 10: '"true"'
Traceback (most recent call last):
  File "C:\Users\joaol\Desktop\conversor_planilha\src\services\salesforce_api.py", line 622, in create_bulk_leads_in_salesforce
    'index': int(parts[1])
             ~~~^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"true"'
2025-05-15 20:44:34 [ERROR] [salesforce_api] - [environment=SANDBOX | timestamp=2025-05-15T20:44:34.766649 | caller=salesforce_api] Erro ao processar leads em massa: invalid literal for int() with base 10: '"true"'
Traceback (most recent call last):
  File "C:\Users\joaol\Desktop\conversor_planilha\src\services\salesforce_api.py", line 622, in create_bulk_leads_in_salesforce
    'index': int(parts[1])
             ~~~^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"true"'
2025-05-15 20:46:31 [ERROR] [salesforce_api] - [environment=SANDBOX | timestamp=2025-05-15T20:46:31.522321 | caller=salesforce_api] Erro ao processar leads em massa: invalid literal for int() with base 10: '"true"'
Traceback (most recent call last):
  File "C:\Users\joaol\Desktop\conversor_planilha\src\services\salesforce_api.py", line 622, in create_bulk_leads_in_salesforce
    'index': int(parts[1])
             ~~~^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"true"'
